export const SET_USER = "SET_USER"
export const LOGIN = "LOGIN"
export const SIGNUP = "SIGNUP"
export const AUTHENTICATED = "AUTHENTICATED"
export const SIGNOUT = "SIGNOUT"
export const SET_PEOPLE_LST = "SET_PEOPLE_LST"